### ISSUE TITLE
feature extraction

### ISSUE THREAD

**Issue by BigBuffa1o** [UARK-AICV/TAPG-AgentEnvInteration#1]
I have tried to implement your code on my custom dataset.May i ask what model you use for extract 2048 dim video C3D feature?i have look into C3D and 3D resnet pretrained model and it doesn't have layer of 2048 dim output(which i find is 512,4096 etc),if i change the model layer it means i cant use pretrained model,have you use some post processing on the feature output or can you give me some guide of the feature extraction how i can get my own video feature for the training

**Comment by Rui-hue** [comment]
Hello, have you received any guidance on feature extraction? Can you share it? Thank you! This is my email:645249607@qq.com @BigBuffa1o
